add ansible/test_connection.yaml
mo124121/isucon-o11y pull request #15
Opened 2024-11-28 13:43 UTC by HideakiTakechi

2024-11-29 21:26 UTC, mo124121 requested changes

2024-11-29 21:26 UTC, mo124121 commented on ansible/inventory.yaml
本番はよくわからないのですが、
過去問AMIだとubuntuによるログインになりそうです。

2024-12-01 01:38 UTC, HideakiTakechi commented on ansible/inventory.yaml
去年の本番はisuconログインでした。
（cloudformation_contest.yamlでUserData: write_files: - path: /home/isucon/.ssh/authorized_keysに鍵書き込み。
　過去問IAMは各自で公開鍵指定するためununtu作法に従ってる気がします。）
by hidetake@PullReq練習中。PullReq #16を別に送りました。

2024-12-02 12:23 UTC, mo124121 commented on ansible/inventory.yaml
そうですね…
このリポジトリはあくまでo11y関連のものをまとめているだけなので、
このリポジトリを使って開発コード等を管理することを想定してないです。

その用途に関するものであればOKですが、
そうでない場合はマージはすべきではないかなと思います。

2024-12-03 01:38 UTC, HideakiTakechi commented on ansible/inventory.yaml
そうですね。こちらのプルリクはクローズします。

2024-12-03 01:38 UTC, closed without merging